---
- hosts: all
  gather_facts: false
  #connection: local
  vars:
    ansible_user: vagrant
    ansible_password: vagrant
    
  tasks:
  - name: Fetch LIFE.tgz
    fetch:
      src: "/home/vagrant/files/test.yml"
      dest: "/var/lib/awx/files"
      flat: true
