---
- hosts: all
  gather_facts: false
  #connection: local
  vars:
    ansible_user: vagrant
    ansible_password: vagrant
    
  tasks:
  - name: Fetch LIFE.tgz
    fetch:
      src: "/root/files/test.yml"
      dest: "/root/results/"
      flat: true
